package br.edu.unidavi.oscar.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of filme.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Filme implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** filCodigo. */
	private Integer filCodigo;

	/** titulo. */
	private String titulo;

	/** genero. */
	private Short genero;

	/** paisOrigem. */
	private String paisOrigem;

	/** The set of elenco. */
	private Set<Elenco> elencoSet;

	/** The set of indicacao. */
	private Set<Indicacao> indicacaoSet;

	/**
	 * Constructor.
	 */
	public Filme() {
		this.elencoSet = new HashSet<Elenco>();
		this.indicacaoSet = new HashSet<Indicacao>();
	}

	/**
	 * Set the filCodigo.
	 * 
	 * @param filCodigo
	 *            filCodigo
	 */
	public void setFilCodigo(Integer filCodigo) {
		this.filCodigo = filCodigo;
	}

	/**
	 * Get the filCodigo.
	 * 
	 * @return filCodigo
	 */
	public Integer getFilCodigo() {
		return this.filCodigo;
	}

	/**
	 * Set the titulo.
	 * 
	 * @param titulo
	 *            titulo
	 */
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	/**
	 * Get the titulo.
	 * 
	 * @return titulo
	 */
	public String getTitulo() {
		return this.titulo;
	}

	/**
	 * Set the genero.
	 * 
	 * @param genero
	 *            genero
	 */
	public void setGenero(Short genero) {
		this.genero = genero;
	}

	/**
	 * Get the genero.
	 * 
	 * @return genero
	 */
	public Short getGenero() {
		return this.genero;
	}

	/**
	 * Set the paisOrigem.
	 * 
	 * @param paisOrigem
	 *            paisOrigem
	 */
	public void setPaisOrigem(String paisOrigem) {
		this.paisOrigem = paisOrigem;
	}

	/**
	 * Get the paisOrigem.
	 * 
	 * @return paisOrigem
	 */
	public String getPaisOrigem() {
		return this.paisOrigem;
	}

	/**
	 * Set the set of the elenco.
	 * 
	 * @param elencoSet
	 *            The set of elenco
	 */
	public void setElencoSet(Set<Elenco> elencoSet) {
		this.elencoSet = elencoSet;
	}

	/**
	 * Add the elenco.
	 * 
	 * @param elenco
	 *            elenco
	 */
	public void addElenco(Elenco elenco) {
		this.elencoSet.add(elenco);
	}

	/**
	 * Get the set of the elenco.
	 * 
	 * @return The set of elenco
	 */
	public Set<Elenco> getElencoSet() {
		return this.elencoSet;
	}

	/**
	 * Set the set of the indicacao.
	 * 
	 * @param indicacaoSet
	 *            The set of indicacao
	 */
	public void setIndicacaoSet(Set<Indicacao> indicacaoSet) {
		this.indicacaoSet = indicacaoSet;
	}

	/**
	 * Add the indicacao.
	 * 
	 * @param indicacao
	 *            indicacao
	 */
	public void addIndicacao(Indicacao indicacao) {
		this.indicacaoSet.add(indicacao);
	}

	/**
	 * Get the set of the indicacao.
	 * 
	 * @return The set of indicacao
	 */
	public Set<Indicacao> getIndicacaoSet() {
		return this.indicacaoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((filCodigo == null) ? 0 : filCodigo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Filme other = (Filme) obj;
		if (filCodigo == null) {
			if (other.filCodigo != null) {
				return false;
			}
		} else if (!filCodigo.equals(other.filCodigo)) {
			return false;
		}
		return true;
	}

}
