package br.edu.unidavi.oscar.model;

import java.io.Serializable;

/**
 * Model class of vencedor.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vencedor implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ano. */
	private Short ano;

	/** categoria. */
	private Categoria categoria;

	/** filme. */
	private Filme filme;

	/**
	 * Constructor.
	 */
	public Vencedor() {
	}

	public Vencedor(Short ano, Categoria categoria, Filme filme) {
		super();
		this.ano = ano;
		this.categoria = categoria;
		this.filme = filme;
	}

	/**
	 * Set the ano.
	 * 
	 * @param ano
	 *            ano
	 */
	public void setAno(Short ano) {
		this.ano = ano;
	}

	/**
	 * Get the ano.
	 * 
	 * @return ano
	 */
	public Short getAno() {
		return this.ano;
	}

	/**
	 * Set the categoria.
	 * 
	 * @param categoria
	 *            categoria
	 */
	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	/**
	 * Get the categoria.
	 * 
	 * @return categoria
	 */
	public Categoria getCategoria() {
		return this.categoria;
	}

	/**
	 * Set the filme.
	 * 
	 * @param filme
	 *            filme
	 */
	public void setFilme(Filme filme) {
		this.filme = filme;
	}

	/**
	 * Get the filme.
	 * 
	 * @return filme
	 */
	public Filme getFilme() {
		return this.filme;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ano == null) ? 0 : ano.hashCode());
		result = prime * result + ((categoria == null) ? 0 : categoria.hashCode());
		result = prime * result + ((filme == null) ? 0 : filme.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Vencedor other = (Vencedor) obj;
		if (ano == null) {
			if (other.ano != null) {
				return false;
			}
		} else if (!ano.equals(other.ano)) {
			return false;
		}
		if (categoria == null) {
			if (other.categoria != null) {
				return false;
			}
		} else if (!categoria.equals(other.categoria)) {
			return false;
		}
		if (filme == null) {
			if (other.filme != null) {
				return false;
			}
		} else if (!filme.equals(other.filme)) {
			return false;
		}
		return true;
	}

}
